-- 1. Create live_sessions table
CREATE TABLE IF NOT EXISTS live_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  last_ping TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  primary_emotion TEXT,
  engagement_score FLOAT,
  status TEXT DEFAULT 'Online'
);

-- 2. Create interventions table if missing
CREATE TABLE IF NOT EXISTS interventions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  instructor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Enable RLS
ALTER TABLE live_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE interventions ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies
DROP POLICY IF EXISTS "Public Access" ON live_sessions;
CREATE POLICY "Public Access" ON live_sessions FOR ALL USING (true);

DROP POLICY IF EXISTS "Public Access" ON interventions;
CREATE POLICY "Public Access" ON interventions FOR ALL USING (true);
